### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by davecastlevania** [spereverde/codecademy-expresso#4]
Great job with this project! I really like how you were able to maintain the code and keep it nice and clean while also being able to design this to the specs. You did a good job also with using your thinking to make different endpoints for this Node application. I don't really have other suggestions outside of maybe making other pages link together with this site so you can show it off as a portfolio piece. Great job!

Summary: beyond expectations

**Comment by spereverde** [comment]
Thanks for the review! It took some work but I'm glad I got this far :-)
